[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = { version = "0.2.95", features = ["serde"] }

[lib]
crate-type = ["cdylib", "rlib"]
